# Generated by Django 2.1.4 on 2019-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
                ('editors_choice', models.CharField(max_length=10)),
            ],
        ),
    ]
